language: android
before_install:
  - nvm install 8
  - node --version
install:
  - npm i
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script:
  - npm run test
  -  'if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ "$TRAVIS_BRANCH" == "master" ]; then yarn appr; fi'
deploy:
  skip_cleanup: true
  provider: releases
  file: $TRAVIS_BUILD_DIR/android/app/build/outputs/apk/app-release-unsigned.apk
  on:
    repo: frontmesh/practical-weather
    tags: true

