language: node_js
node_js:
- node
cache: yarn
install:
- npm i
script:
- npm run test
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn appr; fi
before_install:
- openssl aes-256-cbc -K $encrypted_c9ff443a4d87_key -iv $encrypted_c9ff443a4d87_iv
  -in .env.enc -out .env -d
- openssl aes-256-cbc -K $encrypted_3093ddd21e4e_key -iv $encrypted_3093ddd21e4e_iv
  -in .env.enc -out .env -d
