language: node_js
node_js:
- node
cache: yarn
install:
- npm i
script:
- npm run test:ci
- if [ "$TRAVIS_BRANCH" == "master" ]; then yarn appr; fi
before_install:
- if [ "$TRAVIS_BRANCH" == "master" ]; then openssl aes-256-cbc -K $encrypted_c9ff443a4d87_key -iv $encrypted_c9ff443a4d87_iv
  -in .env.enc -out .env -d; fi
